version: '2'
services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  web:
    image: alach1/web-app:${WEB_VER}
    environment:
      APPLICATION_SECRET: QCY?tAnfk?aZ?iwr
      POSTGRES_HOST: database
    stdin_open: true
    tty: true
    links:
    - database:mongo
    labels:
      io.rancher.container.pull_image: always
      foo: bar
  ComputerDBlb:
    image: rancher/lb-service-haproxy:v0.7.15
    ports:
    - 9000:9000/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'

