version: '2'
catalog:
  name: Computer database Application
  version: v0.0.1
  questions:
  - variable: WEB_VER
    label: Web version?
    required: true
    default: 1.0.0
    type: string
services:
  database:
    scale: 1
    start_on_create: true
  web:
    scale: 2
    start_on_create: true
  ComputerDBlb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: web
        source_port: 9000
        target_port: 9000
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000

